#!/usr/bin/env bash

# Config gcloud project
gcloud config set project emulator

# Start emulator
gcloud beta emulators datastore start \
  --data-dir=/opt/data \
  --host-port=0.0.0.0:8081 \
  --consistency=1.0
