#!/usr/bin/env bash

options=${options:1}
# Check for datastore options
while [ ! $# -eq 0 ]
do
  case "$1" in
    --store-on-disk)
      options="$options --store-on-disk"
      shift
      ;;
    --no-store-on-disk)
      options="$options --no-store-on-disk"
      shift
      ;;
    --consistency=*)
      consistency=${1#*=}
      options="$options --consistency=$consistency"
      shift
      ;;
    *)
      echo "Invalid option: $1. Use: --store-on-disk, --no-store-on-disk, --consistency=[0.0-1.0]"
      exit 1
      ;;
  esac
done

# Config gcloud project
gcloud config set project emulator

# Start emulator
gcloud beta emulators datastore start \
  --data-dir=/opt/data \
  --host-port=0.0.0.0:8081 \
  ${options}
